site_name: 'backstage-example'

nav:
  - Home: README.md
  - Getting Started: getting-started.md
  - Kafka: 
    - Consumed Topics: kafka/topics-consumed.md
    - Provided Topics: kafka/topics-provided.md

plugins:
  - techdocs-core
